
# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# Manipulação de rotas para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Variáveis de ambiente
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Garantir que os pacotes problemáticos sejam processados corretamente
[build.processing]
  skip_processing = false
