
import { SupermarketProduct } from './types';

export const sampleSupermarketProducts: SupermarketProduct[] = [
  {
    id: '1',
    name: 'Arroz Branco Tio João',
    category_type: 'groceries',
    price: 1200,
    cost: 900,
    stock: 50,
    description: 'Arroz branco de qualidade premium, pacote de 1kg',
    barcode: '7891234567890',
    user_id: 'system',
    brand: 'Tio João',
    unit: 'pacote',
    discount_percentage: 0
  },
  {
    id: '2',
    name: 'Feijão Preto Camil',
    category_type: 'groceries',
    price: 950,
    cost: 700,
    stock: 45,
    description: 'Feijão preto de qualidade superior, pacote de 1kg',
    barcode: '7891234567891',
    user_id: 'system',
    brand: 'Camil',
    unit: 'pacote',
    discount_percentage: 5
  },
  {
    id: '3',
    name: 'Leite Integral Parmalat',
    category_type: 'dairy',
    price: 750,
    cost: 550,
    stock: 80,
    description: 'Leite integral UHT, embalagem Tetra Pak de 1L',
    barcode: '7891234567892',
    user_id: 'system',
    brand: 'Parmalat',
    unit: 'caixa',
    discount_percentage: 0
  },
  {
    id: '4',
    name: 'Queijo Mussarela Fatiado',
    category_type: 'dairy',
    price: 1800,
    cost: 1400,
    stock: 25,
    description: 'Queijo mussarela fatiado, pacote de 200g',
    barcode: '7891234567893',
    user_id: 'system',
    brand: 'Tirolez',
    unit: 'pacote',
    discount_percentage: 0
  },
  {
    id: '5',
    name: 'Maçã Gala',
    category_type: 'produce',
    price: 850,
    cost: 600,
    stock: 100,
    description: 'Maçã gala fresca, preço por kg',
    barcode: '7891234567894',
    user_id: 'system',
    unit: 'kg',
    discount_percentage: 0
  },
  {
    id: '6',
    name: 'Banana Prata',
    category_type: 'produce',
    price: 650,
    cost: 450,
    stock: 120,
    description: 'Banana prata fresca, preço por kg',
    barcode: '7891234567895',
    user_id: 'system',
    unit: 'kg',
    discount_percentage: 0
  },
  {
    id: '7',
    name: 'Pão Francês',
    category_type: 'bakery',
    price: 1200,
    cost: 800,
    stock: 60,
    description: 'Pão francês fresco, preço por kg',
    barcode: '7891234567896',
    user_id: 'system',
    unit: 'kg',
    discount_percentage: 0
  },
  {
    id: '8',
    name: 'Bolo de Chocolate',
    category_type: 'bakery',
    price: 2500,
    cost: 1800,
    stock: 15,
    description: 'Bolo de chocolate caseiro, unidade',
    barcode: '7891234567897',
    user_id: 'system',
    unit: 'unidade',
    discount_percentage: 0
  },
  {
    id: '9',
    name: 'Refrigerante Coca-Cola',
    category_type: 'beverages',
    price: 950,
    cost: 700,
    stock: 90,
    description: 'Refrigerante Coca-Cola, garrafa de 2L',
    barcode: '7891234567898',
    user_id: 'system',
    brand: 'Coca-Cola',
    unit: 'garrafa',
    discount_percentage: 10
  },
  {
    id: '10',
    name: 'Água Mineral sem Gás',
    category_type: 'beverages',
    price: 350,
    cost: 200,
    stock: 150,
    description: 'Água mineral sem gás, garrafa de 500ml',
    barcode: '7891234567899',
    user_id: 'system',
    brand: 'Indaiá',
    unit: 'garrafa',
    discount_percentage: 0
  },
  {
    id: '11',
    name: 'Frango Inteiro',
    category_type: 'meat',
    price: 2200,
    cost: 1700,
    stock: 30,
    description: 'Frango inteiro congelado, preço por kg',
    barcode: '7891234567900',
    user_id: 'system',
    brand: 'Sadia',
    unit: 'kg',
    discount_percentage: 0
  },
  {
    id: '12',
    name: 'Carne Moída',
    category_type: 'meat',
    price: 3200,
    cost: 2500,
    stock: 25,
    description: 'Carne moída bovina, embalagem de 500g',
    barcode: '7891234567901',
    user_id: 'system',
    unit: 'pacote',
    discount_percentage: 0
  },
  {
    id: '13',
    name: 'Detergente Líquido',
    category_type: 'household',
    price: 450,
    cost: 300,
    stock: 80,
    description: 'Detergente líquido para louça, frasco de 500ml',
    barcode: '7891234567902',
    user_id: 'system',
    brand: 'Ypê',
    unit: 'frasco',
    discount_percentage: 15
  },
  {
    id: '14',
    name: 'Sabão em Pó',
    category_type: 'household',
    price: 1800,
    cost: 1300,
    stock: 40,
    description: 'Sabão em pó para roupas, embalagem de 1kg',
    barcode: '7891234567903',
    user_id: 'system',
    brand: 'Omo',
    unit: 'caixa',
    discount_percentage: 0
  },
  {
    id: '15',
    name: 'Shampoo',
    category_type: 'personal',
    price: 1500,
    cost: 1100,
    stock: 35,
    description: 'Shampoo para todos os tipos de cabelo, frasco de 350ml',
    barcode: '7891234567904',
    user_id: 'system',
    brand: 'Seda',
    unit: 'frasco',
    discount_percentage: 0
  },
  {
    id: '16',
    name: 'Sabonete em Barra',
    category_type: 'personal',
    price: 350,
    cost: 200,
    stock: 100,
    description: 'Sabonete em barra suave, 90g',
    barcode: '7891234567905',
    user_id: 'system',
    brand: 'Dove',
    unit: 'unidade',
    discount_percentage: 0
  },
  {
    id: '17',
    name: 'Pizza Congelada de Calabresa',
    category_type: 'frozen',
    price: 2200,
    cost: 1600,
    stock: 20,
    description: 'Pizza congelada sabor calabresa, 450g',
    barcode: '7891234567906',
    user_id: 'system',
    brand: 'Sadia',
    unit: 'unidade',
    discount_percentage: 0
  },
  {
    id: '18',
    name: 'Sorvete de Chocolate',
    category_type: 'frozen',
    price: 2800,
    cost: 2000,
    stock: 15,
    description: 'Sorvete de chocolate, pote de 2L',
    barcode: '7891234567907',
    user_id: 'system',
    brand: 'Kibon',
    unit: 'pote',
    discount_percentage: 0
  },
  {
    id: '19',
    name: 'Batata Chips',
    category_type: 'snacks',
    price: 750,
    cost: 500,
    stock: 60,
    description: 'Batata chips tradicional, pacote de 90g',
    barcode: '7891234567908',
    user_id: 'system',
    brand: 'Ruffles',
    unit: 'pacote',
    discount_percentage: 0
  },
  {
    id: '20',
    name: 'Chocolate ao Leite',
    category_type: 'snacks',
    price: 650,
    cost: 400,
    stock: 70,
    description: 'Chocolate ao leite, tablete de 90g',
    barcode: '7891234567909',
    user_id: 'system',
    brand: 'Garoto',
    unit: 'unidade',
    discount_percentage: 0
  }
];

export function importSampleSupermarketProducts(userId: string): SupermarketProduct[] {
  return sampleSupermarketProducts.map(product => ({
    ...product,
    user_id: userId
  }));
}
